In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import StratifiedKFold

In [4]:
df = pd.read_csv('data.csv')
dfFifa = df[['Name','Age','Overall','Potential']]
print(dfFifa)

                       Name  Age  Overall  Potential
0                  L. Messi   31       94         94
1         Cristiano Ronaldo   33       94         94
2                 Neymar Jr   26       92         93
3                    De Gea   27       91         93
4              K. De Bruyne   27       91         92
5                 E. Hazard   27       91         91
6                 L. Modrić   32       91         91
7                 L. Suárez   31       91         91
8              Sergio Ramos   32       91         91
9                  J. Oblak   25       90         93
10           R. Lewandowski   29       90         90
11                 T. Kroos   28       90         90
12                 D. Godín   32       90         90
13              David Silva   32       90         90
14                 N. Kanté   27       89         90
15                P. Dybala   24       89         94
16                  H. Kane   24       89         91
17             A. Griezmann   27       89     

In [7]:
dftarget = dfFifa[dfFifa['Age'] <= 25][dfFifa['Overall'] >= 80][dfFifa['Potential'] >= 80]
labeltarget = np.array([1]*len(dftarget))
dftarget['Label'] = labeltarget
print(dftarget.head(20))

                   Name  Age  Overall  Potential  Label
9              J. Oblak   25       90         93      1
15            P. Dybala   24       89         94      1
16              H. Kane   24       89         91      1
25            K. Mbappé   19       88         95      1
42            S. Umtiti   24       87         92      1
43            M. Icardi   25       87         90      1
45             P. Pogba   25       87         91      1
47            R. Lukaku   25       87         89      1
55              L. Sané   22       86         92      1
56       Bernardo Silva   23       86         91      1
57              Ederson   24       86         90      1
60          R. Sterling   23       86         89      1
62            R. Varane   25       86         91      1
63          M. Verratti   25       86         89      1
77          M. Škriniar   23       85         92      1
78  S. Milinković-Savić   23       85         90      1
79        Marco Asensio   22       85         92

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  """Entry point for launching an IPython kernel.


In [9]:
print(labeltarget)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [11]:
dfnontarget = dfFifa.drop(dftarget.index)
labelnontarget = np.array([0]*len(dfnontarget))
dfnontarget['Label'] = labelnontarget
print(dfnontarget)

                       Name  Age  Overall  Potential  Label
0                  L. Messi   31       94         94      0
1         Cristiano Ronaldo   33       94         94      0
2                 Neymar Jr   26       92         93      0
3                    De Gea   27       91         93      0
4              K. De Bruyne   27       91         92      0
5                 E. Hazard   27       91         91      0
6                 L. Modrić   32       91         91      0
7                 L. Suárez   31       91         91      0
8              Sergio Ramos   32       91         91      0
10           R. Lewandowski   29       90         90      0
11                 T. Kroos   28       90         90      0
12                 D. Godín   32       90         90      0
13              David Silva   32       90         90      0
14                 N. Kanté   27       89         90      0
17             A. Griezmann   27       89         90      0
18            M. ter Stegen   26       8

In [13]:
dflabeled = dftarget.append(dfnontarget, ignore_index = True)
print(dflabeled)

                       Name  Age  Overall  Potential  Label
0                  J. Oblak   25       90         93      1
1                 P. Dybala   24       89         94      1
2                   H. Kane   24       89         91      1
3                 K. Mbappé   19       88         95      1
4                 S. Umtiti   24       87         92      1
5                 M. Icardi   25       87         90      1
6                  P. Pogba   25       87         91      1
7                 R. Lukaku   25       87         89      1
8                   L. Sané   22       86         92      1
9            Bernardo Silva   23       86         91      1
10                  Ederson   24       86         90      1
11              R. Sterling   23       86         89      1
12                R. Varane   25       86         91      1
13              M. Verratti   25       86         89      1
14              M. Škriniar   23       85         92      1
15      S. Milinković-Savić   23       8

In [15]:
x_train, x_test, y_train, y_test = train_test_split(
    dflabeled[['Age', 'Overall', 'Potential']],
    dflabeled['Label'],
    test_size = .1
)

In [17]:
print(len(x_train))

16386


In [18]:
print(len(x_test))

1821


In [25]:
k = StratifiedKFold(n_splits = 50, random_state=None, shuffle=False)
Data = dflabeled[['Age', 'Overall', 'Potential']].values
print(Data)

[[25 90 93]
 [24 89 94]
 [24 89 91]
 ...
 [16 47 67]
 [17 47 66]
 [16 46 66]]


In [27]:
print(k)

StratifiedKFold(n_splits=50, random_state=None, shuffle=False)


In [29]:
#K-Fold
for train_index, test_index in k.split(Data, dflabeled['Label']):
    x_train = Data[train_index]
    y_train = dflabeled['Label'][train_index]

In [31]:
#Testing Cross Validation Score
print('Akurasi Model Regresi Logistik:',
    round(cross_val_score(
    LogisticRegression(solver = 'lbfgs', multi_class = 'auto'),
    x_train,
    y_train
).mean() * 100), 'persen')

print('Akurasi Model Decision Tree:',
    round(cross_val_score(
    DecisionTreeClassifier(),
    x_train,
    y_train
).mean() * 100), 'persen')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


Akurasi Model Regresi Logistik: 93.0 persen
Akurasi Model Decision Tree: 89.0 persen


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


In [33]:
def k_value():
    k = round((len(x_train)+len(x_test)) ** .5)
    if (k % 2 == 0):
        return k + 1
    else:
        return k

# print(k_value())
print('Akurasi Model KNN:',
    round(cross_val_score(
    KNeighborsClassifier(n_neighbors = k_value()),
    x_train,
    y_train
).mean() * 100), 'persen')

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:2053: FutureWarning: You should specify a value for 'cv' instead of relying on the default value. The default value will change from 3 to 5 in version 0.22.
  warnings.warn(CV_WARNING, FutureWarning)


Akurasi Model KNN: 94.0 persen


In [35]:
##players selection
dftarget = dfFifa[dfFifa['Age'] <= 25][dfFifa['Overall'] >= 80][dfFifa['Potential'] >= 80]
labeltarget = 'Rekrut'
dftarget['Label'] = labeltarget

dfnontarget = dfFifa.drop(dftarget.index)
labelnontarget = 'Tidak direkrut'
dfnontarget['Label'] = labelnontarget

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  


In [37]:
dflabeled = dftarget.append(dfnontarget, ignore_index = True)

In [39]:
x_train, x_test, y_train, y_test = train_test_split(
    dflabeled[['Age', 'Overall', 'Potential']],
    dflabeled['Label'],
    test_size = .1
)

In [41]:
print(len(x_train)) 

16386


In [43]:
print(len(x_test))

1821


In [45]:
#Define k_value
def k_value():
    k = round((len(x_train)+len(x_test)) ** .5)
    if (k % 2 == 0):
        return k + 1
    else:
        return k
print(k_value())

135


In [47]:
model = KNeighborsClassifier(               
    n_neighbors = k_value()
)

In [48]:
#Fitting Model
model.fit(x_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=None, n_neighbors=135, p=2,
           weights='uniform')

In [51]:
#Accuracy
print(model.score(x_test, y_test))

0.9983525535420099


In [54]:
#Andik Vermansyah
print(model.predict([[27, 87, 90]]))

['Tidak direkrut']


In [56]:
#Awan Setho Raharjo
print(model.predict([[22, 75, 83]])) 

['Tidak direkrut']


In [58]:
#Bambang Pamungkas
print(model.predict([[38, 85, 75]]))

['Tidak direkrut']


In [60]:
#Cristian Gonzales
print(model.predict([[43, 90, 85]])) 

['Tidak direkrut']


In [62]:
#Egy Maulana Vikri
print(model.predict([[18, 88, 90]]))

['Rekrut']


In [64]:
#Evan Dimas
print(model.predict([[24, 85, 87]]))

['Rekrut']


In [66]:
# Febri Hariyadi
print(model.predict([[23, 77, 80]]))

['Tidak direkrut']


In [68]:
#Hansamu Yama Pranata
print(model.predict([[24, 82, 85]]))

['Rekrut']


In [70]:
#Septian David Maulana
print(model.predict([[22, 83, 80]]))

['Tidak direkrut']


In [71]:
#Stefano Lilipaly
print(model.predict([[29, 88, 86]]))

['Tidak direkrut']
